### ISSUE TITLE
how to toggle close?

### ISSUE THREAD

**Issue by Kakashi-sama** [yaminncco/vue-sidebar-menu#282]
@update:collapsed="onToggleCollapse"

I have added this prop. I get
runtime-dom.esm-bundler.js:225 Uncaught (in promise) NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (runtime-dom.esm-bundler.js:225:12)
    at processCommentNode (runtime-core.esm-bundler.js:4466:7)
    at patch (runtime-core.esm-bundler.js:4425:9)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4889:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:305:19)
    at setupRenderEffect (runtime-core.esm-bundler.js:5003:5)
    at mountComponent (runtime-core.esm-bundler.js:4801:7)
    at processComponent (runtime-core.esm-bundler.js:4766:9)
    at patch (runtime-core.esm-bundler.js:4441:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4889:11)

**Comment by yaminncco** [comment]
I don't know why you're getting that error but to toggle the sidebar use `v-model:collapsed` then you can toggle the ref

```
<template>
  <sidebar-menu
    v-model:collapsed="collapsed"
  />
</template>

<script setup>
import { ref } from 'vue'

const collapsed = ref(false)

function toggle() {
  collapsed.value = !collapsed.value
}
</script>
```
